name: develop-workflow

on:
  push:
    branches: [ develop ]

jobs:
    setup:
      name: Setup project
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node: [14]
      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - name: Get origin develop
          uses: actions/checkout@v2
        - name: Cache node modules
          uses: actions/cache@v1
          env:
            cache-name: cache-node-modules
          with:
            path: node_modules
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-build-${{ env.cache-name }}-
              ${{ runner.os }}-build-
              ${{ runner.os }}-
        - name: Install dependencies
          run: npm ci
    test:
      name: Run tests
      runs-on: ubuntu-latest
      needs: [setup]
      strategy:
        matrix:
          node: [14]
      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - name: Get origin develop
          uses: actions/checkout@v2
        - name: Cache node modules
          uses: actions/cache@v1
          env:
            cache-name: cache-node-modules
          with:
            path: node_modules
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-build-${{ env.cache-name }}-
              ${{ runner.os }}-build-
              ${{ runner.os }}-
        - name: Tests coverage
          run: npm run test-ci
    build:
      name: Build project
      runs-on: ubuntu-latest
      needs: [setup, test]
      strategy:
        matrix:
          node: [14]
      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - name: Get origin develop
          uses: actions/checkout@v2
        - name: Cache node modules
          uses: actions/cache@v1
          env:
            cache-name: cache-node-modules
          with:
            path: node_modules
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-build-${{ env.cache-name }}-
              ${{ runner.os }}-build-
              ${{ runner.os }}-
        - name: Build
          run: npm run build
